language: go

go:
- 1.15.1

git:
  depth: 1

notifications:
  email: false

before_install:
- export COVERALLS_SERVICE_JOB_ID=$( TRAVIS_JOB_ID )
- export COVERALLS_SERVICE_NAME="jsoncjson go code coverage"
- go get github.com/mattn/goveralls

script:
- make lint
- make test.coverage
- $GOPATH/bin/goveralls -service=travis-ci
